plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "org.jetbrains.kotlin.jvm"
}

repositories {
    maven {
        url "https://maven.terraformersmc.com/releases/"
    }

    maven {
        url "https://jitpack.io/" // Fabric ASM
        content {
            excludeGroup "io.github.fabricators_of_create"
        }
    }

    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }

    maven {
        name = "Geckolib"
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
    }

    maven {
        name = "Greenhouse Maven"
        url = 'https://maven.greenhouse.lgbt/releases/'
    }

    maven { url "https://mvn.devos.one/releases/" } // Porting Lib

    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release" // Reach Entity Attributes (Required by Porting Lib)
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven/"
    }

    maven {
        name = "Debug Utils (GitLab)"
        url = "https://gitlab.com/api/v4/projects/21830712/packages/maven/"
    }

    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }

    implementation project(":common")
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "net.fabricmc:fabric-language-kotlin:$fabric_kotlin_version+kotlin.$kotlin_version"
    modImplementation ("maven.modrinth:hybrid-aquatic:${aquatic_version}-fabric") {
        transitive = false
    }
    modApi "software.bernie.geckolib:geckolib-fabric-$geckolib_version"
    include modImplementation("com.jamieswhiteshirt:reach-entity-attributes:$reach_entity_attributes_version")

    implementation 'org.jetbrains:annotations:25.0.0'

    //We still have to load the loader-specific version of any mods included in common
    modRuntimeOnly "io.github.flemmli97:debugutils:$minecraft_version-$debug_utils_version-fabric"
    modRuntimeOnly "maven.modrinth:carpet:$carpet_version"
    modImplementation("vectorwing:FarmersDelight:${fdrf_version}") {exclude(group: "net.fabricmc")}

    modApi("com.terraformersmc:modmenu:${modmenu_version}")
}

// Set up datagen and export the output to be consumed by other projects
configurations {
    datagenOutput
}

fabricApi {
    configureDataGeneration {
        setModId("$mod_id")
        outputDirectory = file("src/generated/resources")
    }

    dependencies {
        datagenOutput files(runDatagen)
    }
}

loom {
    var accessWidenerFile = file("src/main/resources/${mod_id}.accesswidener")
    if (accessWidenerFile.exists()) {
        accessWidenerPath.set(accessWidenerFile)
    } else {
        println "No access widener exists!"
    }

    mixin {
        useLegacyMixinAp = true
        defaultRefmapName.set("${mod_id}.refmap.json")
    }


    compileKotlin {
        source(project(":common").sourceSets.main.allSource)
        inputs.file "../gradle.properties"
    }

    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}