# Integration Mods
# Loaded into the dev runs only. Never compiled into or shipped with the mod.
#
# Modrinth version IDs, not version numbers.
# https://api.modrinth.com/v2/project/<slug>/version?loaders=["neoforge"]&game_versions=["1.21.1"]

hybrid_aquatic_version=Uz0jRbE8

# Their hard dependencies.

geckolib_version=1.20.1:4.8.2
curios_version=IPQlZkz1
lithostitched_version=srPoHKt8
biolith_version=3wmaz5qg